#!/usr/bin/env python3
"""Generate MulticlassGlyphIcons.lua: glyph effect-spell id -> display icon path.

The 'glyphs' wire sends a glyph's effect-spell id (GlyphProperties.SpellId). Its GetSpellInfo icon is the
generic inscription icon, NOT the glyph's real display rune -- the native GlyphFrame pulls that from
GlyphProperties.SpellIconID -> SpellIcon.dbc, a field AzerothCore does not load. We bake that resolution
here so the custom Glyphs ring shows the same rune the native UI would, for a class that isn't projected.

Usage: gen_glyph_icons.py <dbc-dir> <out.lua>   (dbc-dir holds GlyphProperties.dbc + SpellIcon.dbc)
"""
import struct
import sys


def load(path):
    d = open(path, "rb").read()
    _, nrec, _, recsize, strsize = struct.unpack("<4sIIII", d[:20])
    base = 20 + nrec * recsize
    return nrec, recsize, d[20:base], d[base:base + strsize]


def cstr(strs, off):
    end = strs.find(b"\x00", off)
    return strs[off:end].decode("latin-1")


def main(dbcdir, out):
    n, rs, recs, strs = load(dbcdir + "/SpellIcon.dbc")
    icon = {}
    for i in range(n):
        Id, off = struct.unpack_from("<II", recs, i * rs)
        icon[Id] = cstr(strs, off)

    n, rs, recs, strs = load(dbcdir + "/GlyphProperties.dbc")
    by_spell = {}
    for i in range(n):
        _, spell, _, icon_id = struct.unpack_from("<IIII", recs, i * rs)
        if spell == 0:
            continue
        path = icon.get(icon_id, "") if icon_id else ""
        if path:                       # a real icon always wins a spellId shared by placeholder rows
            by_spell[spell] = path
        elif spell not in by_spell:
            by_spell[spell] = ""

    rows = sorted((s, p) for s, p in by_spell.items() if p)
    lines = [
        "-- GENERATED by client-patch/tools/gen_glyph_icons.py from GlyphProperties.dbc + SpellIcon.dbc.",
        "-- Maps a glyph's effect-spell id (what the 'glyphs' wire sends) to its display icon (the native rune",
        "-- from GlyphProperties.SpellIconID, which AzerothCore does not load). Do NOT edit by hand.",
        "MulticlassUI = MulticlassUI or {};",
        "MulticlassUI.GLYPH_ICON = {",
    ]
    for s, p in rows:
        lines.append('\t[%d] = "%s",' % (s, p.replace("\\", "\\\\")))
    lines.append("};")
    text = "\r\n".join(lines) + "\r\n"
    open(out, "wb").write(text.encode("ascii"))
    print("wrote %s (%d entries)" % (out, len(rows)))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
