#!/usr/bin/env python3
"""Generate MulticlassTalentData.lua from Talent.dbc + TalentTab.dbc (WDBC).

Input DBCs default to the named server copies (client/vanilla stores them under
hashed names). Output is written with CRLF + TAB to match the overlay byte
conventions. Re-run only when the talent DBCs change.
"""
import struct, sys, os

DEF_TALENT = "/home/charlie/azerothcore/client/server/dbc/Talent.dbc"
DEF_TALENTTAB = "/home/charlie/azerothcore/client/server/dbc/TalentTab.dbc"
OUT = os.path.join(os.path.dirname(__file__),
                   "../overlay/Interface/FrameXML/MulticlassTalentData.lua")


def read_dbc(path):
    with open(path, "rb") as f:
        data = f.read()
    magic, nrec, nfield, rsize, sblock = struct.unpack_from("<4sIIII", data, 0)
    if magic != b"WDBC":
        raise SystemExit("not a WDBC file: %s" % path)
    if rsize != nfield * 4:
        raise SystemExit("unexpected record size in %s" % path)
    recs_off = 20
    str_off = recs_off + nrec * rsize
    strings = data[str_off:str_off + sblock]
    rows = [struct.unpack_from("<%dI" % nfield, data, recs_off + i * rsize)
            for i in range(nrec)]
    return rows, strings


def get_string(block, off):
    end = block.find(b"\0", off)
    return block[off:end].decode("latin1") if end >= 0 else ""


def class_id_from_mask(mask):
    # Player talent tabs carry a single class bit: 1<<(classId-1). bit_length gives classId.
    if mask == 0 or (mask & (mask - 1)) != 0:
        return 0
    return mask.bit_length()


def main():
    talent_path = sys.argv[1] if len(sys.argv) > 1 else DEF_TALENT
    tab_path = sys.argv[2] if len(sys.argv) > 2 else DEF_TALENTTAB
    talent_rows, _ = read_dbc(talent_path)
    tab_rows, tab_strings = read_dbc(tab_path)

    # TalentTabEntry: 0=id, 20=ClassMask, 21=petTalentMask, 22=tabpage, 23=background(string offset)
    tabs = {}
    for r in tab_rows:
        tab_id, class_mask, pet_mask, page, bg_off = r[0], r[20], r[21], r[22], r[23]
        if pet_mask != 0:
            continue  # pet talent trees are not player class tabs
        class_id = class_id_from_mask(class_mask)
        if class_id == 0:
            continue
        tabs[tab_id] = {"classId": class_id, "page": page,
                        "name": get_string(tab_strings, r[1]),   # field 1 = Name_lang[enUS]
                        "background": get_string(tab_strings, bg_off)}

    # TalentEntry: 0=id, 1=TalentTab, 2=Row, 3=Col, 4..8=RankID[5], 13=DependsOn, 16=DependsOnRank
    talents = {}
    for r in talent_rows:
        tid, tab, row, col = r[0], r[1], r[2], r[3]
        if tab not in tabs:
            continue  # skip pet talents / non-player tabs
        ranks = [r[i] for i in range(4, 9) if r[i] != 0]
        talents[tid] = {"tab": tab, "tier": row, "col": col, "ranks": ranks,
                        "dep": r[13], "depRank": r[16]}

    class_tabs = {}
    for tab_id, t in tabs.items():
        class_tabs.setdefault(t["classId"], []).append(tab_id)
    for c in class_tabs:
        class_tabs[c].sort(key=lambda tid: tabs[tid]["page"])

    lines = []
    W = lines.append
    W("-- GENERATED by client-patch/tools/gen_talent_data.py -- DO NOT EDIT BY HAND.")
    W("MulticlassTalentData = {")
    W("\ttalents = {")
    for tid in sorted(talents):
        t = talents[tid]
        ranks = ",".join(str(s) for s in t["ranks"])
        W("\t\t[%d] = { tab=%d, tier=%d, col=%d, ranks={%s}, dep=%d, depRank=%d },"
          % (tid, t["tab"], t["tier"], t["col"], ranks, t["dep"], t["depRank"]))
    W("\t},")
    W("\ttabs = {")
    for tab_id in sorted(tabs):
        t = tabs[tab_id]
        W("\t\t[%d] = { classId=%d, page=%d, name=\"%s\", background=\"%s\" },"
          % (tab_id, t["classId"], t["page"], t["name"], t["background"]))
    W("\t},")
    W("\tclassTabs = {")
    for c in sorted(class_tabs):
        W("\t\t[%d] = { %s }," % (c, ", ".join(str(t) for t in class_tabs[c])))
    W("\t},")
    W("};")
    W("")  # trailing newline

    with open(OUT, "wb") as f:
        f.write("\r\n".join(lines).encode("ascii"))

    print("player tabs: %d, talents: %d, classes: %d"
          % (len(tabs), len(talents), len(class_tabs)))
    if len(tabs) != 30:
        raise SystemExit("expected 30 player talent tabs, got %d" % len(tabs))


if __name__ == "__main__":
    main()
